contentColumnType: boolean
fieldGroup: 04887042-9aa1-44e9-b100-dace878e95ea
handle: isPrivate
instructions: ''
name: 'is private'
searchable: true
settings:
  default: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
