contentColumnType: string(255)
fieldGroup: 6b8c4a95-1e43-487d-a5aa-66b779ea2fb0
handle: sourceUrl
instructions: ''
name: 'Source Link (Wikipeadia)'
searchable: true
settings:
  maxLength: '255'
  placeholder: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Url
