fieldLayouts:
  4a618146-c30f-4d80-91b3-f9f1dc3de3e8:
    tabs:
      -
        fields:
          0762e6ca-df3a-4005-b2a4-5d1ad76a558d:
            required: false
            sortOrder: 1
        name: Field
        sortOrder: 1
handle: countries
name: Countries
sortOrder: 1
