dateModified: 1553766318
email:
  fromEmail: martin@elfacht.com
  fromName: 'Craft Boiler'
  transportType: craft\mail\transportadapters\Sendmail
fieldGroups:
  1bf68793-4605-4eb8-96e6-148f837f03e9:
    name: Matrix
  2a4ad02c-3617-40e0-9afd-d8a889434899:
    name: Text
  31d18b5e-790f-45d1-a0e8-ad958838bd86:
    name: '_ SEO'
  9981ef49-3927-4035-826d-474f9948d67b:
    name: Tables
  ac30c9c1-7628-4998-bed5-92c1ab01c9f9:
    name: Colors
  af0691bd-53f2-4148-a076-6d31dcab64d4:
    name: Assets
  ffb8d24c-cd85-431a-bd39-282f11e7f9e1:
    name: Controls
fields:
  1a66228a-39b8-4997-a728-10e69931ecd4:
    contentColumnType: text
    fieldGroup: 31d18b5e-790f-45d1-a0e8-ad958838bd86
    handle: seoDescription
    instructions: ''
    name: Beschreibung
    searchable: '1'
    settings:
      charLimit: ''
      code: false
      columnType: text
      initialRows: '4'
      multiline: '1'
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  d7f2745f-9bfc-4af4-b99b-087771791fb5:
    contentColumnType: text
    fieldGroup: 2a4ad02c-3617-40e0-9afd-d8a889434899
    handle: excerpt
    instructions: ''
    name: Auszug
    searchable: true
    settings:
      charLimit: ''
      code: ''
      columnType: text
      initialRows: '3'
      multiline: '1'
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  db7bbe78-5705-4eae-8d7b-e3b456175686:
    contentColumnType: text
    fieldGroup: 31d18b5e-790f-45d1-a0e8-ad958838bd86
    handle: seoTitle
    instructions: ''
    name: Titel
    searchable: '1'
    settings:
      charLimit: ''
      code: false
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  f0a2337d-f703-4420-b65b-8faa4f2e979a:
    contentColumnType: string
    fieldGroup: 31d18b5e-790f-45d1-a0e8-ad958838bd86
    handle: seoImage
    instructions: 1200x630
    name: 'SEO Image'
    searchable: '1'
    settings:
      allowedKinds:
        - image
      defaultUploadLocationSource: ''
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      restrictFiles: '1'
      selectionLabel: ''
      singleUploadLocationSource: ''
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: '1'
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
globalSets:
  c6c5b2a6-e8e6-4463-b242-d611ba885c82:
    fieldLayouts:
      b2280801-6c4f-49ed-a3f9-621b9c2ba788:
        tabs:
          -
            fields:
              1a66228a-39b8-4997-a728-10e69931ecd4:
                required: '0'
                sortOrder: '2'
              db7bbe78-5705-4eae-8d7b-e3b456175686:
                required: '0'
                sortOrder: '1'
              f0a2337d-f703-4420-b65b-8faa4f2e979a:
                required: '0'
                sortOrder: '3'
            name: Inhalt
            sortOrder: '1'
    handle: seo
    name: SEO
plugins:
  architect:
    enabled: '1'
    licenseKey: null
    schemaVersion: 2.0.0
    settings: null
  cookies:
    enabled: '1'
    licenseKey: null
    schemaVersion: 1.0.0
    settings: null
  minify:
    enabled: '1'
    licenseKey: null
    schemaVersion: 1.0.0
    settings: null
  redactor:
    enabled: '1'
    licenseKey: null
    schemaVersion: 2.2.2
    settings: null
sections:
  0303d94b-b2fb-40f8-aadb-51308be503c3:
    enableVersioning: '1'
    entryTypes:
      189e8b0d-271a-49b0-8684-488c6466f0cd:
        handle: rss
        hasTitleField: '0'
        name: RSS
        sortOrder: '1'
        titleFormat: '{section.name|raw}'
        titleLabel: null
    handle: rss
    name: RSS
    propagateEntries: '1'
    siteSettings:
      f462de77-5b6f-48ff-a87b-9c52bde3696d:
        enabledByDefault: '1'
        hasUrls: '1'
        template: rss
        uriFormat: rss
    type: single
  0691c30c-d4cb-4bd4-8e6a-1c6a698273ea:
    enableVersioning: '1'
    entryTypes:
      ddbc8d41-ddd2-46c0-b467-046dbff788d8:
        fieldLayouts:
          2b93096a-1cc8-47d8-a201-8f80bf3fca49:
            tabs:
              -
                fields:
                  79474aea-ca87-4588-8358-e6a73b4ec89e:
                    required: '0'
                    sortOrder: '1'
                name: Inhalt
                sortOrder: '1'
        handle: searchResults
        hasTitleField: '0'
        name: Suche
        sortOrder: '1'
        titleFormat: '{section.name|raw}'
        titleLabel: null
    handle: searchResults
    name: Suche
    propagateEntries: '1'
    siteSettings:
      f462de77-5b6f-48ff-a87b-9c52bde3696d:
        enabledByDefault: '1'
        hasUrls: '1'
        template: sections/search/results
        uriFormat: search
    type: single
  1f12c45b-1b19-4449-9402-fc335630bd72:
    enableVersioning: true
    entryTypes:
      57ac73b8-3bbc-4c12-95d5-dd668c4e560d:
        fieldLayouts:
          1ec6e050-0853-48ee-bd10-a1c9ee380030:
            tabs:
              -
                fields:
                  d7f2745f-9bfc-4af4-b99b-087771791fb5:
                    required: false
                    sortOrder: 1
                name: Einstellungen
                sortOrder: 1
              -
                fields:
                  1a66228a-39b8-4997-a728-10e69931ecd4:
                    required: false
                    sortOrder: 2
                  db7bbe78-5705-4eae-8d7b-e3b456175686:
                    required: false
                    sortOrder: 1
                  f0a2337d-f703-4420-b65b-8faa4f2e979a:
                    required: false
                    sortOrder: 3
                name: SEO
                sortOrder: 2
        handle: page
        hasTitleField: true
        name: Seite
        sortOrder: 1
        titleFormat: ''
        titleLabel: Titel
    handle: pages
    name: Seiten
    propagateEntries: true
    siteSettings:
      f462de77-5b6f-48ff-a87b-9c52bde3696d:
        enabledByDefault: false
        hasUrls: true
        template: pages/_router
        uriFormat: '{slug}'
    structure:
      maxLevels: ''
      uid: 4717ebdc-85a3-4213-919b-34a8e622206a
    type: structure
siteGroups:
  5057a2b5-4e1c-4a4e-8c98-772176c1049e:
    name: 'Craft Boiler'
sites:
  f462de77-5b6f-48ff-a87b-9c52bde3696d:
    baseUrl: '@web/'
    handle: default
    hasUrls: '1'
    language: de
    name: 'Craft Boiler'
    primary: '1'
    siteGroup: 5057a2b5-4e1c-4a4e-8c98-772176c1049e
    sortOrder: '1'
system:
  edition: solo
  live: true
  name: $SYSTEM_NAME
  schemaVersion: 3.1.25
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: ''
  photoVolumeUid: null
  requireEmailVerification: true
